"""empty message

Revision ID: 9772235bfb11
Revises: 
Create Date: 2024-07-04 17:11:45.940631

"""
from typing import Sequence, Union

from alembic import op
import bot
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9772235bfb11'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created_at', bot.types.unix.Unixepoch(), nullable=False),
    sa.Column('updated_at', bot.types.unix.Unixepoch(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.Numeric(scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
